# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [self-hosted, arm]
    strategy:
      fail-fast: false

    steps:
    - name: Clean working directory
      shell: bash
      run: |
        echo "Cleaning up previous run"
        rm -rf "$GITHUB_WORKSPACE/*"
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python3.7 -m pip install --upgrade pip
        python3.7 -m pip install virtualenv
        python3.7 -m virtualenv venv
        source venv/bin/activate
        pip install -e .[develop]
        python setup.py bdist_wheel
        python setup.py sdist
    - name: Test with pytest
      run: |
        source venv/bin/activate
        pytest
    - name: Archive prebuilt wheel
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
 

